Silent Option now true by default
sindresorhus/hook-std pull request #10
Opened 2017-02-16 00:24 UTC by Jflima92

2017-02-16 16:52 UTC, sindresorhus requested changes

2017-02-16 16:52 UTC, sindresorhus commented on index.js
> +		opts.silent = true;
You should never modify user-supplied objects. This can all kinds of issues when the object is reused between calls, something users could do.

2017-02-16 16:52 UTC, sindresorhus commented on index.js
> +		opts.silent = true;
Instead of all this, just do:

```js
opts = Object.assign({silent: true}, opts);
```

2017-02-16 16:52 UTC, sindresorhus commented on index.js
> -
Don't do unrelated changes.

2017-02-16 16:52 UTC, sindresorhus commented
Thanks for working on this. You also need to update the readme.

2017-02-16 16:53 UTC, sindresorhus commented
GitHub tip: Always reference the issue you're fixing with a sentence like: `Fixes #8`

2017-02-17 20:54 UTC, Jflima92 commented
Hey!
Thanks for the feedback.
You're welcome, glad to help.

2017-02-18 06:43 UTC, sindresorhus approved these changes

2017-02-18 06:44 UTC, merged

2017-02-18 06:47 UTC, sindresorhus commented
Thank you :)