Feature/once option
sindresorhus/hook-std pull request #11
Opened 2017-04-13 21:40 UTC by ruimarques

Hello @sindresorhus !

I hope this is what you where looking for with #1. I wasn't sure so I set its default behavior as false.

I also replaced `new Buffer()` with `Buffer.from()` within the test cases, because that was giving me deprecated errors and breaking the tests. Let me know if that should have been made in a separated PR.

Fixes #1

2017-04-14 12:21 UTC, ruimarques commented on index.js
> +			unhook(std, write);
I am wondering if we are ok to unhook immediately of if we should only do it after `cb2` is called (when write is finished).

2017-04-16 09:22 UTC, sindresorhus commented on index.js
> +			unhook(std, write);
Immediately, otherwise it's not really "once", as there might be more writes before the first write is done flushing.

2017-04-16 09:29 UTC, sindresorhus requested changes
Looks pretty good :)

2017-04-16 09:29 UTC, sindresorhus commented on test.js
> +	m.stdout({silence: false, once: true}, str => {
`silence` => `silence`

2017-04-16 09:29 UTC, sindresorhus commented on index.js
> +}
I would just make this a closure:

```js
const unhook = () => {
	std.write = write;	
};
```

And put it below line 19.

2017-04-16 20:35 UTC, ruimarques commented on test.js
> +	m.stdout({silence: false, once: true}, str => {
Done. After fixing the option name, the test was failing because it was slightly wrong. Had to fix the test.

2017-04-16 20:35 UTC, ruimarques commented on index.js
> +}
Done

2017-04-17 05:15 UTC, sindresorhus requested changes

2017-04-17 05:15 UTC, sindresorhus commented on index.js
> +	return unhook.bind(null);
The `.bind(null)` is moot.

2017-04-17 09:23 UTC, ruimarques commented on index.js
> +	return unhook.bind(null);
Removed

2017-04-17 12:32 UTC, sindresorhus approved these changes

2017-04-17 12:32 UTC, merged

2017-04-17 12:32 UTC, sindresorhus commented
Looks great. Thank you @ruimarques :)

2017-04-17 13:39 UTC, ruimarques commented
Cool!