Add TypeScript Definitions
sindresorhus/hook-std pull request #20
Opened 2018-09-08 12:58 UTC by Codex-

Removed my request from DefinitelyTyped and migrated following your [guide.](https://github.com/sindresorhus/typescript-definition-style-guide)

Hopefully this meets the requirements :)

2018-09-12 08:15 UTC, sindresorhus requested changes

2018-09-12 08:15 UTC, sindresorhus commented on index.d.ts
> +export function stderr(opts: Options, transform: Transform): PromiseUnhook;
`opts` => `options`

2018-09-12 08:15 UTC, sindresorhus commented on index.d.ts
> + * @param transform - the transform function.
Sentences should start with an uppercase character.

2018-09-12 08:15 UTC, sindresorhus commented on index.d.ts
> +export interface PromiseUnhook extends Promise<any> {
I would rather call this `HookPromise` as that's what it is. It's a Promise for the hook.

2018-09-12 08:15 UTC, sindresorhus commented on index.d.ts
> + * unhook() method which, when called, unhooks from a stream
unhook() should be wrapped in backticks.

2018-09-12 08:15 UTC, sindresorhus commented on index.d.ts
> + * the return value of .write(...).
.write(...) should be wrapped in backticks.

2018-09-12 08:15 UTC, sindresorhus commented on index.d.ts
> + * Hooks stdout or alternatively the streams in options.
> alternatively the streams in options.

This is not correct. You're not supposed to use the `streams` option with the `.stdout`/`stderr` methods. I guess that needs to be made clearer in the docs.

2018-09-12 08:15 UTC, sindresorhus commented on index.d.ts
> + * @param transform - the transform function.
> If the parameter description just repeats the parameter name, leave it out.

2018-09-12 08:21 UTC, sindresorhus commented on index.d.ts
> + * second argument.
Don't hard-wrap. Applies to all the comments.

2018-09-12 09:05 UTC, sindresorhus commented on index.d.ts
> +export interface PromiseUnhook extends Promise<any> {
`any` => `void`?

2018-09-12 09:31 UTC, Codex- commented on index.d.ts
> + * unhook() method which, when called, unhooks from a stream
Ah I see, wasn't sure if this was supported, cheers

2018-09-12 09:40 UTC, sindresorhus commented
Let me know if there's anything in the style guide that could be clearer or improved. It's still a work-in-progress :)

2018-09-12 09:58 UTC, Codex- commented on index.d.ts
> + * Hooks stdout or alternatively the streams in options.
Hmmm I suppose that means I should remove these:
`stderr(options: Options, transform: Transform): HookPromise;`
`stdout(options: Options, transform: Transform): HookPromise;`

Would you prefer a second set of options be typed in such a way that doesn't allow options with streams as parameter types for `stdout` and `stderr`?

2018-09-12 10:01 UTC, Codex- commented
Re: the guide. I suppose the main thing I found a little tricky at first was how to use the type assertions correctly, I ended up going through a few other projects to understand the usage more correctly.

2018-09-12 10:09 UTC, sindresorhus commented on index.d.ts
> + * Hooks stdout or alternatively the streams in options.
You could do something like this for just the default export:

```ts
type DefaultOptions = Options & {
	streams?: Writable[];
}

export default function hookStd(options?: DefaultOptions, transform: Transform): PromiseUnhook;
```

And remove `streams` from the `Options` interface

2018-09-12 10:10 UTC, sindresorhus commented
Also note:

> For packages with a default export, use `export default foo;`, not `export = foo;`. You will have to add `module.exports.default = foo;` to the `index.js` file.

2018-09-12 10:10 UTC, sindresorhus commented
You also left out types for the default export.

2018-09-12 10:37 UTC, Codex- commented
Yup I've come to realize this after the comment around the stream options, will sort out soonish :)

2018-09-12 12:16 UTC, Codex- commented on index.d.ts
> + * Hooks stdout or alternatively the streams in options.
I created a `DefaultOptions` interface which extends the `Options` interface to create this typing.

Thanks for the suggestion, have implemented similar, however you can't follow an optional param with a required one.

2018-09-12 12:28 UTC, Codex- commented
I've _hopefully_ this time covered everything :)

2018-09-17 02:18 UTC, Codex- commented
Mistakes were made...

2018-09-17 02:45 UTC, Codex- commented
Should be good now.

2018-09-17 04:30 UTC, Codex- commented on index.d.ts
> + * @param transform - the transform function.
Can you please clarify if this means to remove the whole `@param` doc or just the description?

2018-09-17 04:52 UTC, Codex- commented
Actually I take it back, few issues to look at still, will comment when ready for another review

2018-10-04 22:41 UTC, Codex- commented
Updated with the default export and fixed some typings. I think this is more up to scratch now.

Can you please clarify a couple of things:

`If the parameter description just repeats the parameter name, leave it out.`
Does this mean I should remove all docstring params that are simply `@param transform` or that there shouldn't be a description if the description just repeats the param such as `@param transform the transform function`.


In the [readme](https://github.com/sindresorhus/hook-std#hookstdoptions-transform) it specifies `unhooks both stdout and stderr` but if you use custom or additional streams it unhooks these too, should it in that case read something more along the lines of `unhooks both stdout, stderr or any specified streams`

Cheers

2018-10-13 10:07 UTC, sindresorhus commented
> Does this mean I should remove all docstring params that are simply @param transform

Yes

> In the readme it specifies unhooks both stdout and stderr but if you use custom or additional streams it unhooks these too, should it in that case read something more along the lines of unhooks both stdout, stderr or any specified streams

Maybe just:

> Unhooks the streams in the `streams` option.

2018-10-13 10:12 UTC, sindresorhus commented on index.d.ts
> +export function stdout(options: Options, transform: Transform): HookPromise;
Why make this an overload instead of just marking `options` as optional?

2018-10-13 12:23 UTC, Codex- commented on index.d.ts
> +export function stdout(options: Options, transform: Transform): HookPromise;
Optional parameters cannot precede required parameters.

2018-10-13 13:58 UTC, sindresorhus commented on index.d.ts
> +export function stdout(options: Options, transform: Transform): HookPromise;
Hmm, ok. That's a lame limitation of TS...

2018-11-15 11:29 UTC, Codex- commented
Just wondering if there were any pending changes you were wanting that I have possibly missed?

2018-11-20 14:32 UTC, sindresorhus approved these changes

2018-11-20 14:32 UTC, merged

2018-11-20 14:32 UTC, sindresorhus commented
Thank you :)

2018-11-20 20:33 UTC, Codex- commented
Great, thanks Sindre!